version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile

    stdin_open: true
    tty: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
 
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app

    ports:
      - "8080:8080"

    command: npm run serve
